### ISSUE TITLE
New build needed

### ISSUE THREAD

**Issue by octvcdrc** [jc21/docker-electroneumd#3]
Hi,

Can you trigger a new build ? :)

There's a kinda urgent security update : https://www.facebook.com/electroneum/posts/1965665463695422
(Unfortunatly i can't find the issue on their github...)

Thanks !

**Comment by jc21** [comment]
No problem. I got the email today and rebuilt straight away. The `latest` tag is good to go.

**Comment by octvcdrc** [comment]
Sorry I should have checked before opening the issue.
