### ISSUE TITLE
ARM portability? 

### ISSUE THREAD

**Issue by jonathanmf** [jc21/docker-electroneumd#5]
Hi,
I would love to make it run on a raspberry docker swarm but the package i not ARM compatible. Have you planned to build it? 
Thx for your work ;)
Jo

**Comment by jc21** [comment]
This is technically possible, although I don't have the ability to build or test an ARM image.

If you wanted to give it a try, here's where to start:

1. Open terminal on your ARM OS
2. `git clone https://github.com/jc21/docker-electroneumd.git && cd docker-electroneumd`
3. Edit the `Dockerfile` and replace the first line with `FROM armv7/armhf-ubuntu`
4. `docker build -t etn-arm .`
5. If successful, run it and let me know how you go

The electroneum codebase should apparently identify that you're building on ARM.

**Comment by jonathanmf** [comment]
Hi,

Thx for all those informations! The build failed here : 

```
> Step 7/17 : RUN set -x   && buildDeps='       ca-certificates       cmake       g++       git       libboost1.58-all-dev       libssl-dev       make       pkg-config   '   && apt-get -qq update   && apt-get -qq --no-install-recommends install $buildDeps
>  ---> Running in 5077a5dbaf37
> + buildDeps=       ca-certificates       cmake       g++       git       libboost1.58-all-dev       libssl-dev       make       pkg-config   
> + apt-get -qq update
> E: The repository 'http://ports.ubuntu.com/ubuntu-ports yakkety Release' does no longer have a Release file.
> E: The repository 'http://ports.ubuntu.com/ubuntu-ports yakkety-updates Release' does no longer have a Release file.
> E: The repository 'http://ports.ubuntu.com/ubuntu-ports yakkety-backports Release' does no longer have a Release file.
> E: The repository 'http://ports.ubuntu.com/ubuntu-ports yakkety-security Release' does no longer have a Release file.
> The command '/bin/sh -c set -x   && buildDeps='       ca-certificates       cmake       g++       git       libboost1.58-all-dev       libssl-dev       make       pkg-config   '   && apt-get -qq update   && apt-get -qq --no-install-recommends install $buildDeps' returned a non-zero code: 100
> 
```

**Comment by jc21** [comment]
I think that `armv7/armhf-ubuntu` docker base image might not be up to date. Can't see anything else that will be easy to replace it with. If you go with alpine arm images, you'll have to investigate the right packages for compiling the source.
